"""Position ledger receipts and safe-prefix sequence policy.

Revision ID: 0013
Revises: 0012

The adapter's table-lock barrier waits out every INSERT before reading at
READ COMMITTED. CACHE 1 prevents another connection retaining lower IDs;
GENERATED ALWAYS forbids ordinary callers supplying preallocated IDs.
Administrators must not override/reseed the sequence while ingestion runs.
Existing accounting is not backfilled: the adapter rejects a checkpoint
without complete receipts rather than inventing historical attribution.
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE fills ALTER COLUMN ledger_seq SET GENERATED ALWAYS")
    op.execute("ALTER TABLE fills ALTER COLUMN ledger_seq SET CACHE 1")
    # 0012 allowed explicit IDs. Advance, never rewind, the generator so
    # those existing rows cannot later be followed by a lower generated ID.
    op.execute("""
        SELECT setval(pg_get_serial_sequence('fills', 'ledger_seq'),
                      (SELECT max(ledger_seq) FROM fills), true)
        WHERE (SELECT max(ledger_seq) FROM fills) >= COALESCE(
            pg_sequence_last_value(pg_get_serial_sequence('fills', 'ledger_seq')::regclass), 1)
    """)
    op.create_table(
        "position_fill_receipts",
        sa.Column("ledger_seq", sa.BigInteger(), sa.ForeignKey("fills.ledger_seq"), primary_key=True),
        sa.Column("execution_mode", sa.String(16), nullable=False),
        sa.Column("execution_venue", sa.String(32), nullable=False),
        sa.Column("venue_fill_id", sa.String(128), nullable=False),
        sa.Column("position_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("positions.position_id"), nullable=False),
        sa.Column("fill_data", postgresql.JSONB(), nullable=False),
        sa.Column("trading_day", sa.Date(), nullable=False),
        sa.Column("gross_pnl", sa.Numeric(), nullable=False),
        sa.UniqueConstraint("execution_venue", "venue_fill_id", name="uq_position_receipts_fill_key"),
        sa.CheckConstraint("(execution_venue = 'simulated') = (execution_mode IN ('backtest', 'simulated'))",
                           name="ck_position_receipts_mode_venue"),
    )
    op.create_index("ix_position_fill_receipts_execution_mode", "position_fill_receipts", ["execution_mode"])


def downgrade():
    # Dropping durable attribution would make an applied checkpoint unrecoverable.
    if op.get_bind().execute(sa.text("SELECT EXISTS (SELECT 1 FROM position_fill_receipts)")).scalar():
        raise RuntimeError("Cannot downgrade 0013 with applied position receipts")
    op.drop_table("position_fill_receipts")
    op.execute("ALTER TABLE fills ALTER COLUMN ledger_seq SET GENERATED BY DEFAULT")
